create table MOCK_DATA (
	id INT,
	user_id VARCHAR(50),
	group_id VARCHAR(50),
	creatAt DATE,
	active VARCHAR(50)
);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (1, 'Fluphenazine Hydrochloride', 'atorvastatin calcium', '11/27/2024', true);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (2, 'DOCUSATE SODIUM', 'Ibuprofen', '10/9/2025', true);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (3, 'Adenosinum cyclophosphoricum, Adrenalinum, Adrenocorticotrophin, Allium cepa, Ambrosia artemisiaefolia, Cichorium intybus, Conium maculatum, Cortisone aceticum, Euphrasia officinalis, Fagopyrum esculentum, Galphimia glauca, Hedera helix, Histaminum hydrochloricum, Kali muriaticum, Mucosa nasalis suis, Natrum muriaticum, RNA, Rumex crispus, Sabadilla, Secale cornutum', 'Bismuth subsalicylate', '11/18/2025', false);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (4, 'nitroglycerin', 'Sotalol Hydrochloride', '4/1/2025', false);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (5, 'Octinoxate and Oxybenzone', 'dolutegravir sodium, abacavir sulfate, lamivudine', '8/26/2025', true);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (6, 'Chamomilla Cupro 3 Special Order', 'Amoxicillin', '10/17/2025', true);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (7, 'DOCUSATE SODIUM', 'SIMETHICONE', '8/30/2025', true);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (8, 'Levonorgestrel and Ethinyl Estradiol', 'Benzocaine', '10/23/2025', true);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (9, 'Hydrocodone Bitartrate and Acetaminophen', 'METHYL UNDECENOYL LEUCINATE', '10/22/2025', true);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (10, 'Trandolapril', 'zinc oxide, titanium dioxide', '9/16/2025', true);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (11, 'OCTINOXATE, OXYBENZONE, TITANIUM DIOXIDE', 'Horseradish', '4/19/2025', true);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (12, 'COLISTIMETHATE SODIUM', 'Fluocinonide', '10/24/2025', true);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (13, 'BENZOYL PEROXIDE', 'TITANIUM DIOXIDE', '3/18/2025', true);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (14, 'Levofloxacin', 'Octinoxate, Titanium Dioxide, and Zinc Oxide', '11/18/2025', false);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (15, 'TITANIUM DIOXIDE', 'fexofenadine hcl', '8/25/2025', false);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (16, 'divalproex sodium', 'Bupivacaine Hydrochloride', '11/9/2025', true);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (17, 'Bisoprolol Fumarate', 'Carvedilol', '12/20/2024', false);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (18, 'Avobenzone and Octinoxate', 'White Petroleum', '7/22/2025', false);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (19, 'Carvedilol', 'Buspirone hydrochloride', '1/20/2025', true);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (20, 'OLANZAPINE', 'Guaifenesin', '1/26/2025', true);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (21, 'ETHYL ALCOHOL', 'Sodium fluoride', '8/23/2025', false);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (22, 'Sertraline Hydrochloride', 'TRICLOSAN', '8/2/2025', true);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (23, 'lacosamide', 'Omeprazole', '11/11/2025', false);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (24, 'Brain (bovine),', 'FERRIC OXIDE RED', '7/3/2025', false);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (25, 'Butorphanol Tartrate', 'Ibuprofen, Pseudoephedrine HCl', '7/4/2025', false);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (26, 'Iodine Bush', 'MAGNESIUM HYDROXIDE', '8/17/2025', true);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (27, 'Metformin hydrochloride', 'BUPIVACAINE HYDROCHLORIDE', '6/3/2025', false);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (28, 'Imipramine Hydrochloride', 'Candesartan cilexetil', '5/6/2025', false);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (29, 'desvenlafaxine', 'ECHINACEA PURPUREA', '5/21/2025', false);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (30, 'TOXICODENDRON RADICANS LEAF', 'HYDROXYZINE PAMOATE', '3/4/2025', false);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (31, 'Gemfibrozil', 'Dimethicone', '10/22/2025', true);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (32, 'desipramine hydrochloride', 'Heparin Sodium', '1/8/2025', true);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (33, 'NOT APPLICABLE', 'Octinoxate and Oxybenzone', '10/20/2025', false);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (34, 'APIS MELLIFERA, URTICA URENS, SODIUM CHLORIDE, and ARSENIC TRIOXIDE', 'montelukast sodium', '12/4/2024', true);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (35, 'HORSE CHESTNUT,ALUMINUM OXIDE,SEMECARPUS ANACARDIUM JUICE,BARIUM CARBONATE,BOS TAURUS CEREBELLUM,GINKGO,POTASSIUM PHOSPHATE, DIBASIC.', 'rasagiline mesylate', '4/8/2025', false);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (36, 'Hydrocodone Bitartrate and Homatropine Methylbromide', 'Oxybenzone, Octinoxate', '2/16/2025', false);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (37, 'Acetaminophen, Dextromethorphan HBr, Doxylamine succinate', 'Chlorpheniramine Maleate', '12/24/2024', false);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (38, 'Aluminum Chlorohydrate', 'blue ridge blueberry', '3/12/2025', true);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (39, 'Guinea Pig Epithelia', 'Cephalexin', '11/15/2025', false);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (40, 'Hydrocodone Bitartrate and Acetaminophen', 'levomefolate calcium, methylcobalamin and acetylcysteine', '7/21/2025', true);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (41, 'Aconitum nap., Arg. nit., Aur.met., Baptisia, Bryonia, Chelidonium majus, Cimicifuga, Conium, Gelsemium, Ignatia, Kali carb., Lachesis, Lilium, Lycopodium, Nat. carb., Nat.mur., Phosphoricum ac., Phosphorus, Picricum ac., Plumb. met., Sepia, Staphysag., Stramonium, Thuja occ., Zinc. met., Chamomilla, Hypericum, Valeriana', 'ALCOHOL', '5/12/2025', false);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (42, 'Air', 'Midazolam Hydrochloride', '9/3/2025', true);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (43, 'Diphenhydramine HCl, Phenylephrine HCl', 'Acyclovir', '12/22/2024', false);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (44, 'Clobetasol Propionate', 'OCTINOXATE and TITANIUM DIOXIDE', '1/1/2025', false);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (45, 'Naphazoline Hydrochloride', 'Methyl Salicylate', '12/5/2024', true);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (46, 'Carbamazepine', 'Metoclopramide', '9/20/2025', true);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (47, 'Amlodipine Besylate', 'PALLADIUM', '3/13/2025', true);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (48, 'Treatment Set TS347628', 'Tolnaftate', '8/28/2025', false);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (49, 'Aluminum Zirconium Octachlorohydrex Gly', 'PRAVASTATIN SODIUM', '4/29/2025', true);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (50, 'URSODIOL', 'Aspirin', '12/10/2024', false);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (51, 'cefotaxime sodium', 'Acetaminophen', '7/12/2025', false);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (52, 'clindamycin palmitate hydrochloride', 'Octinoxate and Titanium Dioxide', '3/12/2025', true);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (53, 'Cetirizine Hydrochloride', 'Triclosan', '9/17/2025', true);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (54, 'Leucovorin Calcium', 'cefadroxil monohydrate', '8/6/2025', false);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (55, 'BENZETHONIUM CHLORIDE', 'Hydralazine Hydrochloride', '1/16/2025', true);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (56, 'Acetaminophen', 'Naproxen Sodium', '8/3/2025', true);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (57, 'topiramate', 'MENTHOL', '6/2/2025', false);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (58, 'Magnesium hydroxide', 'Dextromethorphan HBr,USP', '3/24/2025', true);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (59, 'Famotidine', 'Epirubicin Hydrochloride', '1/12/2025', false);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (60, 'Neomycin and Polymyxin B Sulfates and Bacitracin Zinc', 'Bupropion hydrochloride', '1/24/2025', true);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (61, 'Diltiazem Hydrochloride', 'Dicloxacillin Sodium', '3/6/2025', false);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (62, 'Amoxicillin', 'Amitriptyline Hydrochloride', '6/10/2025', true);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (63, 'Spironolactone', 'Sestamibi', '2/27/2025', true);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (64, 'metoprolol tartrate', 'Famotidine', '7/12/2025', false);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (65, 'Alfalfa, Avena sativa, Baryta carbonica, Baryta Iodata, Baryta muriatica, Calcarea carbonica, Calcarea fluorica, Calcarea phosphorica, Lycopodium clavatum, Thuja occidentalis', 'Bisacodyl', '11/19/2025', true);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (66, 'Oxygen', 'TITANIUM DIOXIDE', '7/14/2025', true);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (67, 'TITANIUM DIOXIDE', 'KEROSENE', '2/16/2025', false);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (68, 'benzocaine', 'difenoxin hydrochloride', '9/27/2025', true);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (69, 'Titanium Dioxide', 'Capsaicin', '10/5/2025', false);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (70, 'Trout', 'LILIUM LANCIFOLIUM BULB', '11/24/2024', true);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (71, 'dextromethorphan polistirex', 'Wart Remover Gel Pen', '12/25/2024', false);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (72, 'Aluminum Chlorohydrate', 'ribavirin', '12/2/2024', true);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (73, 'Paroxetine hydrochloride hemihydrate', 'Avobenzone and Homosalate and Octocrylene and Oxybenzone', '11/21/2025', false);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (74, 'OCTINOXATE, ZINC OXIDE', 'pioglitazone hydrochloride', '12/16/2024', false);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (75, 'Hydromorphone Hydrochloride', 'Droperidol', '9/27/2025', false);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (76, 'Sennosides', 'Tolterodine Tartrate', '1/1/2025', false);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (77, 'OCTINOXATE', 'Oxycodone and Acetaminophen', '10/7/2025', false);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (78, 'Alfalfa, Avena sativa, Chelidonium majus, Aralia quinquefolia, Beta vulgaris, Calendula officinalis, Cuprum aceticum, Echinacea, natrum muriaticum, Oxalis acetosella Paloondo,', 'Mixture of Six Standardized Grasses', '10/2/2025', true);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (79, 'Pyrithione Zinc', 'Iodides tincture', '9/14/2025', false);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (80, 'Carbamazepine', 'RABIES VIRUS STRAIN PM-1503-3M ANTIGEN (PROPIOLACTONE INACTIVATED) and WATER', '5/16/2025', false);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (81, 'Triple Antibiotic Plus Pain Relief', 'Naproxen Sodium', '3/26/2025', false);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (82, 'Acetaminophen, Dextromethorphan Hydrobromide, Doxylamine Succinate', 'Belladonna, Conium maculatum, Dulcamara, Hepar sulphuris calcareum, Kali bichromicum, Mercurius solubilis, Pulsatilla (Vulgaris),', '10/6/2025', true);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (83, 'Aspirin', 'GLYCERIN', '9/29/2025', false);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (84, 'Felodipine', 'Metformin Hydrochloride', '9/26/2025', true);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (85, 'Meloxicam', 'Insulin human', '10/28/2025', true);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (86, 'Octinoxate and Oxybenzone', 'Calcium carbonate', '6/25/2025', false);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (87, 'Black Willow', 'Salt Grass', '3/29/2025', true);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (88, 'Losartan potassium', 'THUJA OCCIDENTALIS LEAFY TWIG', '10/27/2025', false);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (89, 'SALICYLIC ACID', 'Capsicum oleoresin', '12/6/2024', false);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (90, 'ISOSORBIDE MONONITRATE', 'zinc oxide, oxybenzone, and octinoxate', '9/29/2025', true);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (91, 'Flumazenil', 'Rye', '8/21/2025', false);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (92, 'isotretinoin', 'Buspirone Hydrochloride', '12/16/2024', false);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (93, 'propoxyphene napsylate and acetaminophen', 'progesterone', '11/3/2025', false);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (94, 'Gabapentin', 'Bismuth subsalicylate', '10/20/2025', false);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (95, 'Divalproex Sodium', 'OCTINOXATE, OCTISALATE, OCTOCRYLENE, TITANIUM DIOXIDE', '12/28/2024', true);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (96, 'Acetaminophen, Dextromethorphan Hydrobromide, Doxylamine Succinate', 'Lamotrigine', '11/13/2025', false);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (97, 'ARNICA MONTANA', 'Mouse Epithelium', '7/15/2025', true);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (98, 'Ceftriaxone', 'Zolpidem Tartrate', '4/9/2025', true);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (99, 'divalproex sodium', 'DOCUSATE SODIUM', '7/29/2025', true);
insert into MOCK_DATA (id, user_id, group_id, creatAt, active) values (100, 'Etodolac', 'Hydrocortisone', '1/30/2025', true);
